name: build

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Git checkout
                uses: actions/checkout@v3

            -   name: Run shellcheck
                run: ./bin/toolbox self-lint

            -   name: Run tests
                run: ./bin/toolbox self-test
